// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Test.sol";
import "../src/SaikoDarkPoolV2.sol";
import "../src/SaikoDarkPoolStaking.sol";
import "../src/verifiers/Groth16Verifier.sol";
import "./mocks/MockERC20.sol";

contract SaikoDarkPoolV2Test is Test {
    MockERC20 token;
    SaikoDarkPoolStaking staking;
    Groth16Verifier verifier;
    SaikoDarkPoolV2 pool;
    address treasury = address(0xBEEF);
    address alice = address(0xA11CE);
    address bob = address(0xB0B);

    uint256 constant TIER_1 = 10_000_000e18;
    uint256 constant FEE_BPS = 50;
    uint256 constant BPS_DENOMINATOR = 10_000;

    // Mock verifier address for vm.mockCall
    address mockVerifierAddr;

    function setUp() public {
        token = new MockERC20("Saiko", "SAIKO");
        staking = new SaikoDarkPoolStaking(address(token), address(0));
        verifier = new Groth16Verifier();

        // Deploy PoseidonT3 from generated bytecode JSON
        string memory json = vm.readFile("circuits/build/poseidon-bytecodes.json");
        bytes memory bytecode = vm.parseJsonBytes(json, ".PoseidonT3.bytecode");

        address poseidonT3;
        assembly {
            poseidonT3 := create(0, add(bytecode, 0x20), mload(bytecode))
        }
        require(poseidonT3 != address(0), "PoseidonT3 deploy failed");

        pool = new SaikoDarkPoolV2(
            20,
            address(verifier),
            poseidonT3,
            address(token),
            treasury,
            address(staking)
        );
        staking.setPool(address(pool));
    }

    function _depositAs(address user, bytes32 commitment, uint256 amount) internal {
        token.mint(user, amount);
        vm.startPrank(user);
        token.approve(address(pool), amount);
        pool.deposit(commitment, amount);
        vm.stopPrank();
    }

    // --- Deposit tests ---

    function test_deposit_insertsLeaf() public {
        bytes32 commitment = bytes32(uint256(123));
        _depositAs(alice, commitment, TIER_1);

        // After one deposit, nextIndex should be 1
        assertEq(pool.nextIndex(), 1);
        assertEq(pool.commitmentAmount(commitment), TIER_1);
    }

    function test_deposit_feeMath() public {
        bytes32 commitment = bytes32(uint256(456));
        _depositAs(alice, commitment, TIER_1);

        uint256 fee = (TIER_1 * FEE_BPS) / BPS_DENOMINATOR;
        uint256 noteAmount = TIER_1 - fee;
        assertEq(pool.tierBalance(TIER_1), noteAmount);

        // Treasury should have received 90% of fee
        uint256 stakingFee = (fee * 1000) / 10_000;
        uint256 treasuryFee = fee - stakingFee;
        assertEq(token.balanceOf(treasury), treasuryFee);
    }

    function test_deposit_duplicateCommitment_reverts() public {
        bytes32 commitment = bytes32(uint256(789));
        _depositAs(alice, commitment, TIER_1);

        token.mint(alice, TIER_1);
        vm.startPrank(alice);
        token.approve(address(pool), TIER_1);
        vm.expectRevert("Commitment exists");
        pool.deposit(commitment, TIER_1);
        vm.stopPrank();
    }

    function test_deposit_invalidTier_reverts() public {
        bytes32 commitment = bytes32(uint256(101));
        uint256 badAmount = 999e18;
        token.mint(alice, badAmount);
        vm.startPrank(alice);
        token.approve(address(pool), badAmount);
        vm.expectRevert("Invalid tier");
        pool.deposit(commitment, badAmount);
        vm.stopPrank();
    }

    // --- Withdraw tests (mocked verifier) ---

    function test_withdraw_withMockedVerifier() public {
        bytes32 commitment = bytes32(uint256(111));
        _depositAs(alice, commitment, TIER_1);

        bytes32 root = pool.getLastRoot();
        bytes32 nullifierHash = bytes32(uint256(999));

        // Mock the verifier to return true for any proof
        vm.mockCall(
            address(verifier),
            abi.encodeWithSelector(Groth16Verifier.verifyProof.selector),
            abi.encode(true)
        );

        uint256[2] memory pA = [uint256(0), uint256(0)];
        uint256[2][2] memory pB = [[uint256(0), uint256(0)], [uint256(0), uint256(0)]];
        uint256[2] memory pC = [uint256(0), uint256(0)];

        uint256 fee = (TIER_1 * FEE_BPS) / BPS_DENOMINATOR;
        uint256 noteAmount = TIER_1 - fee;

        pool.withdraw(pA, pB, pC, root, nullifierHash, bob, TIER_1);

        assertTrue(pool.nullifierSpent(nullifierHash));
        assertEq(token.balanceOf(bob), noteAmount);
    }

    function test_withdraw_invalidProof_reverts() public {
        bytes32 commitment = bytes32(uint256(222));
        _depositAs(alice, commitment, TIER_1);

        bytes32 root = pool.getLastRoot();
        bytes32 nullifierHash = bytes32(uint256(888));

        // Mock the verifier to return false
        vm.mockCall(
            address(verifier),
            abi.encodeWithSelector(Groth16Verifier.verifyProof.selector),
            abi.encode(false)
        );

        uint256[2] memory pA = [uint256(0), uint256(0)];
        uint256[2][2] memory pB = [[uint256(0), uint256(0)], [uint256(0), uint256(0)]];
        uint256[2] memory pC = [uint256(0), uint256(0)];

        vm.expectRevert("Invalid proof");
        pool.withdraw(pA, pB, pC, root, nullifierHash, bob, TIER_1);
    }

    function test_withdraw_doubleSpend_reverts() public {
        bytes32 commitment = bytes32(uint256(333));
        _depositAs(alice, commitment, TIER_1);

        bytes32 root = pool.getLastRoot();
        bytes32 nullifierHash = bytes32(uint256(777));

        vm.mockCall(
            address(verifier),
            abi.encodeWithSelector(Groth16Verifier.verifyProof.selector),
            abi.encode(true)
        );

        uint256[2] memory pA = [uint256(0), uint256(0)];
        uint256[2][2] memory pB = [[uint256(0), uint256(0)], [uint256(0), uint256(0)]];
        uint256[2] memory pC = [uint256(0), uint256(0)];

        pool.withdraw(pA, pB, pC, root, nullifierHash, bob, TIER_1);

        vm.expectRevert("Already spent");
        pool.withdraw(pA, pB, pC, root, nullifierHash, bob, TIER_1);
    }

    function test_withdraw_unknownRoot_reverts() public {
        bytes32 commitment = bytes32(uint256(444));
        _depositAs(alice, commitment, TIER_1);

        bytes32 fakeRoot = bytes32(uint256(12345));
        bytes32 nullifierHash = bytes32(uint256(666));

        vm.mockCall(
            address(verifier),
            abi.encodeWithSelector(Groth16Verifier.verifyProof.selector),
            abi.encode(true)
        );

        uint256[2] memory pA = [uint256(0), uint256(0)];
        uint256[2][2] memory pB = [[uint256(0), uint256(0)], [uint256(0), uint256(0)]];
        uint256[2] memory pC = [uint256(0), uint256(0)];

        vm.expectRevert("Unknown root");
        pool.withdraw(pA, pB, pC, fakeRoot, nullifierHash, bob, TIER_1);
    }

    // --- Merkle tree tests ---

    function test_merkleTree_rootChangesAfterDeposit() public {
        bytes32 rootBefore = pool.getLastRoot();

        bytes32 commitment = bytes32(uint256(555));
        _depositAs(alice, commitment, TIER_1);

        bytes32 rootAfter = pool.getLastRoot();
        assertTrue(rootBefore != rootAfter);
    }

    function test_merkleTree_isKnownRoot() public {
        bytes32 commitment = bytes32(uint256(666));
        _depositAs(alice, commitment, TIER_1);

        bytes32 root = pool.getLastRoot();
        assertTrue(pool.isKnownRoot(root));
        assertFalse(pool.isKnownRoot(bytes32(uint256(99999))));
    }
}

