/**
 * Saiko DarkPool — TypeScript Types
 *
 * All interfaces used across the DarkPool privacy pool feature.
 * Strict typing — no `any`. All exports are named.
 */

// ─── Zero-Knowledge Proof ─────────────────────────────────────────────────────

/**
 * Groth16/PLONK proof output from snarkjs (or mock during development).
 * Format matches snarkjs fullProve() output.
 */
export interface ZKProof {
  /** Proof element A — elliptic curve point encoded as hex strings */
  readonly pi_a: readonly string[];
  /** Proof element B — G2 point (array of pairs) */
  readonly pi_b: readonly (readonly string[])[];
  /** Proof element C — elliptic curve point encoded as hex strings */
  readonly pi_c: readonly string[];
  /** Public signals passed to the verifier */
  readonly publicSignals: readonly string[];
}

// ─── DarkPool Note ──────────────────────────────────────────────────────────────

/**
 * A DarkPool note is the user's private receipt for a deposit.
 * It is the ONLY way to withdraw funds from the pool.
 * Losing a note means permanent, irrecoverable loss of funds.
 *
 * - secret: random 256-bit value, never leaves the client
 * - nullifier: random 256-bit value, prevents double-spend
 * - commitment: poseidonHash(secret, nullifier), stored on-chain
 * - viewingKey: derived from secret, enables selective disclosure
 */
export interface DarkPoolNote {
  /** Random 256-bit secret. NEVER transmit or log. */
  readonly secret: Uint8Array;
  /** Random 256-bit nullifier. Used to mark deposit as spent on withdrawal. */
  readonly nullifier: Uint8Array;
  /** On-chain commitment: hex-encoded poseidonHash(secret, nullifier) */
  readonly commitment: string;
  /** Deposit amount in SAIKO base units (post-fee amount that entered the pool) */
  readonly amount: bigint;
  /** Tier index (0–3) corresponding to DARKPOOL_TIERS */
  readonly tier: number;
  /** Unix timestamp (ms) of deposit */
  readonly timestamp: number;
  /** Deposit transaction hash */
  readonly txHash: string;
  /** Derived viewing key for selective disclosure — user controls when/if shared */
  readonly viewingKey: Uint8Array;
  /** Whether this note has been spent (nullifier submitted on-chain) */
  readonly isSpent: boolean;
  /** Pool version this note was deposited into ('v2' for legacy, 'v3' for new) */
  readonly poolVersion?: 'v2' | 'v3';
}

// ─── DarkPool Deposit ───────────────────────────────────────────────────────────

/**
 * Result of a DarkPool deposit operation.
 * Contains the generated note and fee breakdown.
 */
export interface DarkPoolDeposit {
  /** The private note generated for this deposit — must be backed up immediately */
  readonly note: DarkPoolNote;
  /** Fee amount deducted (0.5% of tier amount) */
  readonly fee: bigint;
  /** Amount that entered the pool (tier amount minus fee) */
  readonly amountAfterFee: bigint;
  /** Address of the SaikoDarkPool contract that received this deposit */
  readonly poolAddress: string;
}

// ─── DarkPool Withdrawal ────────────────────────────────────────────────────────

/**
 * Parameters and result of a DarkPool withdrawal.
 * The zk-proof proves note ownership without revealing which commitment is spent.
 */
export interface DarkPoolWithdrawal {
  /** Keccak256 hash of the nullifier — submitted on-chain to prevent double-spend */
  readonly nullifierHash: string;
  /** Recipient address for withdrawn funds — can be any address, ideally fresh */
  readonly recipient: string;
  /** Zero-knowledge proof attesting to note ownership */
  readonly proof: ZKProof;
  /** Withdrawal transaction hash (set after broadcast) */
  readonly txHash: string;
}

// ─── Compliance Proof ─────────────────────────────────────────────────────────

/**
 * A compliance proof generated by the user using their viewing key.
 * Enables selective disclosure to auditors, exchanges, or regulators.
 * NEVER auto-generated or transmitted — always user-initiated.
 */
export interface ComplianceProof {
  /** Type of proof being generated */
  readonly type: 'ownership' | 'link' | 'source' | 'innocence';
  /** Transaction hash of the original deposit */
  readonly depositTxHash: string;
  /** Transaction hash of the withdrawal (required for 'link' proof type) */
  readonly withdrawalTxHash?: string;
  /** Serialized proof payload (JSON string) — shared with auditor at user discretion */
  readonly proof: string;
  /** Unix timestamp (ms) when this proof was generated */
  readonly generatedAt: number;
}

// ─── Pool Info ────────────────────────────────────────────────────────────────

/**
 * On-chain and derived state for a single DarkPool (one per tier).
 * Used to display anonymity set size and privacy level to the user.
 */
// ─── Staking ──────────────────────────────────────────────────────────────────

export interface StakingInfo {
  readonly commitment: string;
  readonly stakedAmount: bigint;
  readonly earnedRewards: bigint;
  readonly depositTime: number;
  readonly stakingDurationSeconds: number;
}

export interface StakingGlobalInfo {
  readonly ethRewardPool: bigint;
  readonly totalStaked: bigint;
  readonly rewardPool: bigint;
  readonly estimatedAPY: number;
  readonly rewardPerTokenStored: bigint;
  readonly lastUpdateTime: number;
}

export interface StakingClaimResult {
  readonly commitment: string;
  readonly claimedAmount: bigint;
  readonly recipientAddress: string;
  readonly txHash: string;
}

export class StakingError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'StakingError';
  }
}

// ─── Pool Info ────────────────────────────────────────────────────────────

export interface DarkPoolInfo {
  /** Pool tier amount in SAIKO base units */
  readonly tier: bigint;
  /** Contract address of this pool */
  readonly address: string;
  /** Number of deposits currently in the pool's Merkle tree */
  readonly depositCount: number;
  /** Derived privacy level based on deposit count thresholds */
  readonly privacyLevel: 'low' | 'moderate' | 'strong';
}
